### ISSUE TITLE
I need person having retinal pigmentosa 

### ISSUE THREAD

**Issue by Kesuudaykiran** [Mudassiruddin7/Detection-Of-Retinal-Pigmentosa-In-Paediatric-Age-Patients-Using-CNN-With-Tkinter-Framework#1]
In these project  output showing only person has no retinal pigmentosa 
I need person having affected with retinal pigmentosa

**Comment by Mudassiruddin7** [comment]
I've already mentioned in the end which states that all the required data isn't provided here!!

**Comment by Kesuudaykiran** [comment]
How can I get remaining

**Comment by Mudassiruddin7** [comment]
Check it on kaggle!!
